App\Entity\City:
  properties:
    name:
      - NotBlank:
          groups: ['edit','new']
    latitude:
      - Range:
          min: -90
          max: 90
          groups: ['edit','new']
    longitude:
      - Range:
          min: -180
          max: 180
          groups: ['edit','new']

