App\Entity\Data:
  properties:
    date:
    temperature:
      - NotBlank:
          groups: ['edit', 'new']
      - Range:
          min: -100
          max: 70
          groups: ['edit','new']
    wind:
      - Range:
          min: 0
          max: 1000
          groups: ['edit','new']
    humidity:
      - Range:
          min: 0
          max: 100
          groups: ['edit','new']